services:
  # 基础服务，可根据情况替换成第三方
  wvp_redis:
    container_name: wvp_redis
    build:
      context: ./buildFiles/redis
      dockerfile: Dockerfile
    image: wvp_redis
    restart: always
    environment:
      TZ: ${TZ}
    # 端口映射，非必要
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ${REDIS_DATA}:/data
      - ${REDIS_LOGS}:/logs
      - ${REDIS_CONFIG}:/home/redis/redis.conf:ro
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
  wvp_mysql:
    container_name: wvp_mysql
    build:
      context: ./buildFiles/mysql
      dockerfile: Dockerfile
    image: wvp_mysql
    restart: always # 指定开机重启
    command: 
      --character-set-server=utf8mb4 
      --collation-server=utf8mb4_unicode_ci 
      --explicit_defaults_for_timestamp=true 
      --lower_case_table_names=1
      --max_allowed_packet=128M;
    # 端口映射，非必要
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    volumes:
      - ${MYSQL_CONFIG}:/etc/mysql/conf.d
      - ${MYSQL_LOGS}:/logs
      - ${MYSQL_DATA}:/var/lib/mysql:rw # 挂载数据目录
    healthcheck:
      test: [ "CMD-SHELL","/home/healthcheck.sh" ]
      timeout: 20s
      retries: 20
  wvp_pro:
    container_name: wvp_pro
    image: wvp_pro
    build:
      context: ./buildFiles/wvp
      dockerfile: Dockerfile
    environment:
      TZ: ${TZ}
      SIP_DOMAIN: ${SIP_DOMAIN}
      SIP_ID: ${SIP_ID}
      SIP_PASSWORD: ${SIP_PASSWORD}
      WVP_IP: ${WVP_IP}
      WVP_PORT: ${WVP_PORT}
      SIP_IP: ${SIP_IP}
      SHOW_IP: ${SHOW_IP}
      SDP_IP: ${SDP_IP}
      ZLM_IP: ${ZLM_IP}
      ZLM_PORT: ${ZLM_PORT}
      WVP_DB_PATH: ${WVP_DB_PATH}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PWD: ${REDIS_PASSWORD}
      DRUID_USER: ${DRUID_USER}
      DRUID_PASS: ${DRUID_PASS}
      SIP_PORT: ${SIP_PORT}
      ASSIST_PORT: ${ASSIST_PORT}
    ports:
      - ${SIP_PORT}:${SIP_PORT}
      - ${SIP_PORT}:${SIP_PORT}/udp
      - ${WVP_PORT}:${WVP_PORT}

    volumes:
      - ${BASE_PATH}/config/wvp:/opt/wvp/config
      - ${BASE_PATH}/logs/wvp:/opt/wvp/logs # 保存wvp日志
    healthcheck:
      test: [ "CMD", "curl", "-sS", "http://localhost:18080" ]
      timeout: 10s
      retries: 10
    depends_on:
      wvp_zlm:
        condition: service_healthy
      wvp_mysql:
        condition: service_healthy
      wvp_redis:
        condition: service_healthy
  wvp_zlm:
    container_name: wvp_zlm
    image: wvp_zlm
    build:
      context: ./buildFiles/zlm
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PWD: ${REDIS_PASSWORD}
      ASSIST_PORT: ${ASSIST_PORT}
    ports:
      - "554:554/tcp"
      - "554:554/udp"
      - "443:443"
      - "8000:8000"
      - "8000:8000/udp"
      - "1935:1935"
      - "9000:9000"
      - "9000:9000/udp"
      - "322:322"
      - "${ZLM_PORT}:80" # 如果zlm的config.ini文件中端口改变，请同步改变此值
      - "10000:10000/tcp"
      - "10000:10000/udp"
      - "30000-30500:30000-30500/udp"
      - "18081:18081" # assist的web端口
    volumes:
      - ${BASE_PATH}/config/zlm:/opt/media/conf
      - ${RECORD_PATH}:/opt/media/record:rw # 录像保存目录  /opt/wvp/config这个地址如果需要更改，请同步更改wvp中的application.yml文件中的media.record-path
      - ${BASE_PATH}/logs/zlm/media:/opt/media/bin/log # 保存zlm日志
    healthcheck:
      test: [ "CMD", "curl", "-sS", "http://localhost/index/api/version" ] # 检查ZLMediaKit是否正常运行,端口号默认为80，如果修改了config.ini中的端口，请同步修改此处
      timeout: 10s
      retries: 10
