# 基础镜像
FROM mysql
# author
MAINTAINER connor

# 执行sql脚本
ADD ./db/init.sql /docker-entrypoint-initdb.d/init.sql
ADD ./healthcheck.sh /home/healthcheck.sh

RUN chown -R mysql:mysql /docker-entrypoint-initdb.d/init.sql 
RUN chmod +x /home/healthcheck.sh
EXPOSE 3306
CMD ["mysqld"]
